//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ogrenci()
        {
            this.Tbl_Notlar = new HashSet<Tbl_Notlar>();
        }
    
        public byte Ogrenci_Id { get; set; }
        public string Ogrenci_Ad { get; set; }
        public string Ogrenci_Soyad { get; set; }
        public Nullable<byte> Ogrenci_Kulup_Id { get; set; }
        public string Ogrenci_Fotograf { get; set; }
        public string Ogrenci_Cinsiyet { get; set; }
    
        public virtual Tbl_Kulupler Tbl_Kulupler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notlar> Tbl_Notlar { get; set; }
    }
}
